#!/bin/bash

STANDARD="PSR12"
BIN="./vendor/bin"

echo
echo "PHP_CodeSniffer pre-commit hook – commit with the --no-verify option to skip the hook"
echo

# Check whether PHP_CodeSniffer can be found
if [ ! -f "$BIN/phpcs" ]
then
	echo "PHP_CodeSniffer not found – is it installed? 'composer require --dev squizlabs/php_codesniffer'"
	echo
	exit 1
fi

# Retrieve staged files
FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD)

# Run the sniffer
echo "Running PHP_CodeSniffer using the $STANDARD standard"
echo $
echo
PHPCS=("make" "check-style")
"${PHPCS[@]}"

# Syntax OK
if [ $? == 0 ]
then
	echo "No violations detected"
	echo
	exit 0
fi

# Syntax Failed
exit 1
